---
- name: Replace mongod config
  notify:
    - Restart mongodb
  diff: false
  ansible.builtin.template:
    src: init.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - mongodb

- name: Replace handlers flush
  ansible.builtin.meta: flush_handlers
  tags:
    - mongodb

- name: Wait after replace
  ansible.builtin.wait_for:
    host: localhost
    port: "{{ mongodb_net_port }}"
    delay: 5
    timeout: 120
  tags:
    - mongodb

- name: Create root user
  ignore_errors: "{{ ansible_check_mode }}"
  community.mongodb.mongodb_user:
    database: admin
    name: "{{ mongodb_root_admin_username }}"
    password: "{{ mongodb_root_admin_password }}"
    update_password: "{{ mongodb_root_update_password }}"
    roles: root
    login_port: "{{ mongodb_net_port | string }}"
  tags:
    - mongodb

- name: Revert mongod config
  notify:
    - Restart mongodb
  diff: false
  ansible.builtin.template:
    src: config.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - mongodb

- name: Revert handlers flush
  ansible.builtin.meta: flush_handlers
  tags:
    - mongodb

- name: Wait after revert
  ansible.builtin.wait_for:
    host: localhost
    port: "{{ mongodb_net_port }}"
    delay: 5
    timeout: 120
  tags:
    - mongodb

...
