---
- name: Check existing install
  register: mongodb_exporter_version_check
  failed_when: false
  changed_when: false
  check_mode: false
  ansible.builtin.shell: /usr/bin/mongodb-exporter --version  2>&1
  tags:
    - mongodb
    - mongodb-exporter

- name: Fact version change
  ansible.builtin.set_fact:
    mongodb_exporter_version_changed: "{{ mongodb_exporter_version_check.rc != 0 or (mongodb_exporter_version_check.stdout_lines is defined and mongodb_exporter_version not in mongodb_exporter_version_check.stdout_lines[1]) }}"
  tags:
    - mongodb
    - mongodb-exporter

- name: Download release tarball
  when:
    - mongodb_exporter_version_changed
  ansible.builtin.unarchive:
    src: "{{ mongodb_exporter_download }}"
    dest: /usr/local/src
    remote_src: true
    owner: root
    group: root
  tags:
    - mongodb
    - mongodb-exporter

- name: Copy exporter binary
  when:
    - mongodb_exporter_version_changed
    - not ansible_check_mode
  notify:
    - Restart mongodb-exporter
  ansible.builtin.copy:
    src: "/usr/local/src/mongodb_exporter-{{ mongodb_exporter_version }}.linux-{{ mongodb_exporter_arch }}/mongodb_exporter"
    dest: /usr/bin/mongodb-exporter
    remote_src: true
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - mongodb
    - mongodb-exporter

- name: Write default config
  notify:
    - Restart mongodb-exporter
  ansible.builtin.template:
    src: exporter/default.j2
    dest: /etc/default/mongodb-exporter
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - mongodb
    - mongodb-exporter

- name: Write service file
  notify:
    - Restart mongodb-exporter
  ansible.builtin.template:
    src: exporter/service.j2
    dest: /etc/systemd/system/mongodb-exporter.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - mongodb
    - mongodb-exporter

- name: Start mongodb-exporter service
  ansible.builtin.systemd:
    name: mongodb-exporter
    state: "{{ 'started' if mongodb_exporter_enabled else 'stopped' }}"
    daemon_reload: true
    masked: false
    enabled: "{{ true if mongodb_exporter_enabled else false }}"
  tags:
    - mongodb
    - mongodb-exporter

- name: Remove install directory
  ansible.builtin.file:
    path: "/usr/local/src/mongodb_exporter-{{ mongodb_exporter_version }}.linux-{{ mongodb_exporter_arch }}"
    state: absent
  tags:
    - mongodb
    - mongodb-exporter

...
